#!/bin/bash
#
# Setup
#
# Setup the Custom Discogs vault with markdown from the user Discogs collection

URL="https://api.discogs.com"
AGE="github.com/doctorfree/MusicPlayerPlus"
UPD=

[ -x Tools/Discogs/mkdiscogs ] || {
  echo "Tools/Discogs/mkdiscogs does not exist or is not executable."
  echo "The Setup script must be run in the Obsidian-Custom-Discogs folder."
  echo "Exiting without performing custom setup."
  exit 1
}

# Get the Discogs username and a Discogs API token
[ -f "${HOME}/.config/mpprc" ] && . "${HOME}/.config/mpprc"

usage() {
  printf "\nUsage: ./Setup [-R] [-U] [-t token] [-u user] [-h]"
  printf "\nWhere:"
  printf "\n\t-R indicates remove intermediate JSON created during previous run"
  printf "\n\t-U indicates perform an update of the Discogs collection"
  printf "\n\t-t 'token' specifies the Discogs API token"
  printf "\n\t-u 'user' specifies the Discogs username"
  printf "\n\t-h displays this usage message and exits\n\n"
  exit 1
}

cleanup=
while getopts "RUt:u:h" flag; do
    case $flag in
        R)
            cleanup=1
            ;;
        U)
            UPD="-U"
            ;;
        t)
            DISCOGS_TOKEN="${OPTARG}"
            ;;
        u)
            DISCOGS_USER="${OPTARG}"
            ;;
        h)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "${cleanup}" ] && {
  echo "Cleaning up any previously created JSON used in generating markdown"
  rm -rf Tools/Discogs/json
  exit 0
}

have_curl=`type -p curl`
have_jq=`type -p jq`

[ "${have_curl}" ] || {
  printf "\nThe 'curl' utility is required but not found in this user's execution path."
  printf "\nVerify that 'curl' is installed and available on this system, add it to PATH,"
  printf "\nor install 'curl'. On most Linux systems 'curl' can be installed with either:"
  printf "\n\tsudo apt install curl"
  printf "\nor"
  printf "\n\tsudo dnf install curl"
  printf "\nOn Mac OS 'curl' can be installed with Homebrew:"
  printf "\n\tbrew install curl\n"
}
[ "${have_jq}" ] || {
  printf "\nThe 'jq' utility is required but not found in this user's execution path."
  printf "\nVerify that 'jq' is installed and available on this system, add it to PATH,"
  printf "\nor install 'jq'. On most Linux systems 'jq' can be installed with either:"
  printf "\n\tsudo apt install jq"
  printf "\nor"
  printf "\n\tsudo dnf install jq"
  printf "\nOn Mac OS 'jq' can be installed with Homebrew:"
  printf "\n\tbrew install jq\n"
}

[ "${have_jq}" ] && [ "${have_curl}" ] || {
  printf "\nSystem requirements not met. Exiting without performing setup.\n"
  exit 1
}

[ "${DISCOGS_USER}" ] || {
  printf "\nDiscogs username required but none found in ~/.config/mpprc"
  printf "\nThe Discogs username can be found by visiting discogs.com. Login then"
  printf "\nuse the dropdown of your user icon in the upper right corner. Click on"
  printf "\n'Profile'. Your Discogs username is the last component of the profile URL."
  printf "\nPlease enter your Discogs username.\n"
  numtries=1
  while true
  do
    read -p "Discogs username: " username
    case ${username} in
      [?]* )
          DISCOGS_USER="${username}"
          curl --stderr /dev/null \
               -A "${AGE}" "${URL}/users/${username}" | \
               grep "User does not exist" > /dev/null && {
                   DISCOGS_USER=
               }
          if [ "${DISCOGS_USER}" ]
          then
            break
          else
            numtries=$((numtries + 1))
            [ ${numtries} -gt 3 ] && {
              echo "Too many failed attempts to set Discogs username. Exiting."
              exit 1
            }
            echo "Discogs user ${username} does not exist. Please try again."
          fi
          ;;
        * ) echo "Please enter a username."
          ;;
    esac
  done
}

[ "${DISCOGS_TOKEN}" ] || {
  printf "\nDiscogs API token not found in ~/.config/mpprc"
  printf "\nLogin to discogs.com and visit:\n"
  printf "\n\thttps://www.discogs.com/settings/developers\n"
  printf "\nto find or generate a Discogs API token.\n"
  printf "\nPlease enter a Discogs API token.\n"
  numtries=1
  while true
  do
    read -p "Discogs API token: " token
    case ${token} in
      [?]* )
          DISCOGS_TOKEN="${token}"
          curl --stderr /dev/null \
               -A "${AGE}" \
               -H "Authorization: Discogs token=${token}" \
               "${URL}/users/${username}" | \
               grep "Invalid consumer token" > /dev/null && {
                   DISCOGS_TOKEN=
               }
          if [ "${DISCOGS_TOKEN}" ]
          then
            break
          else
            numtries=$((numtries + 1))
            [ ${numtries} -gt 3 ] && {
              echo "Too many failed attempts to set Discogs API token. Exiting."
              exit 1
            }
            echo "Invalid Discogs API token: ${token}. Please try again."
          fi
          ;;
        * ) echo "Please enter a Discogs API token."
          ;;
    esac
  done
}

cd Tools/Discogs
./mkdiscogs -a -t "${DISCOGS_TOKEN}" -u "${DISCOGS_USER}" ${UPD}
