#!/bin/bash

cd ..

for artist in */*
do
  [ "${artist}" == "*/*" ] && continue
  [ -d "${artist}" ] || continue
  cd "${artist}"
  for album in *.md
  do
    [ "${album}" == "*.md" ] && continue
    grep "/assets/" ${album} > /dev/null || {
      echo "${artist}/${album}"
    }
  done
  cd ../..
done
